/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarbonBlog: typeof import('~icons/carbon/blog')['default']
    CharmChevronsRight: typeof import('~icons/charm/chevrons-right')['default']
    ClarityEmployeeGroupLine: typeof import('~icons/clarity/employee-group-line')['default']
    Fa6SolidUsersLine: typeof import('~icons/fa6-solid/users-line')['default']
    FlashCard: typeof import('./components/flashCard.vue')['default']
    FluentTasksApp28Regular: typeof import('~icons/fluent/tasks-app28-regular')['default']
    IcBaselineEdit: typeof import('~icons/ic/baseline-edit')['default']
    IconamoonMenuBurgerHorizontalBold: typeof import('~icons/iconamoon/menu-burger-horizontal-bold')['default']
    IcOutlinePersonPin: typeof import('~icons/ic/outline-person-pin')['default']
    IcOutlineSettings: typeof import('~icons/ic/outline-settings')['default']
    IcRoundArrowBack: typeof import('~icons/ic/round-arrow-back')['default']
    IcRoundAttachMoney: typeof import('~icons/ic/round-attach-money')['default']
    IcRoundDashboard: typeof import('~icons/ic/round-dashboard')['default']
    IcSharpAssignment: typeof import('~icons/ic/sharp-assignment')['default']
    IcSharpMenuBook: typeof import('~icons/ic/sharp-menu-book')['default']
    MaterialSymbolsLogin: typeof import('~icons/material-symbols/login')['default']
    MaterialSymbolsNotifications: typeof import('~icons/material-symbols/notifications')['default']
    MaterialSymbolsPlayCircleOutline: typeof import('~icons/material-symbols/play-circle-outline')['default']
    MaterialSymbolsSearch: typeof import('~icons/material-symbols/search')['default']
    MaterialSymbolsShoppingCartOutlineRounded: typeof import('~icons/material-symbols/shopping-cart-outline-rounded')['default']
    MaterialSymbolsToggleOffOutline: typeof import('~icons/material-symbols/toggle-off-outline')['default']
    MdiCards: typeof import('~icons/mdi/cards')['default']
    MdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    MdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    MdiHelpCircle: typeof import('~icons/mdi/help-circle')['default']
    Myclass: typeof import('./components/Myclass.vue')['default']
    PhChalkboardTeacher: typeof import('~icons/ph/chalkboard-teacher')['default']
    PhExam: typeof import('~icons/ph/exam')['default']
    PhSignOutBold: typeof import('~icons/ph/sign-out-bold')['default']
    PhSpeakerHighDuotone: typeof import('~icons/ph/speaker-high-duotone')['default']
    Question: typeof import('./components/question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./components/SidebarLink.vue')['default']
    SolarHandMoneyOutline: typeof import('~icons/solar/hand-money-outline')['default']
    SolarVideoLibraryBroken: typeof import('~icons/solar/video-library-broken')['default']
    SvgSpinners180Ring: typeof import('~icons/svg-spinners/180-ring')['default']
    TablerUsersGroup: typeof import('~icons/tabler/users-group')['default']
    UilAngleDown: typeof import('~icons/uil/angle-down')['default']
  }
}
